name: Renovate bot
on:
  workflow_dispatch:
  schedule:
  - cron: "0 16 * * *"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: renovate-${{ github.event.repository.name }}
    container:
      image: reg.cluster.internal/randomcoww/renovate:latest@sha256:3587f3d558bca3b7053f34c99e0fe3b063a25f10decfc2974ab4f69e7f85d000
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
    - name: Check for updates
      env:
        RENOVATE_PLATFORM: github
        RENOVATE_AUTODISCOVER: false
        # RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }} # pass RENOVATE_TOKEN from runner
        RENOVATE_CONFIG_FILE: /tmp/renovate.json
      run: |
        cat > $RENOVATE_CONFIG_FILE <<EOF
        {
          "repositories": [
            "${{ github.repository }}"
          ]
        }
        EOF

        exec renovate-entrypoint.sh renovate